# Generated by Django 5.2.12 on 2026-03-26 12:10

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WordModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.CharField(db_index=True, max_length=255)),
                ('language', models.CharField(default='en', max_length=10)),
                ('phonetic', models.CharField(blank=True, max_length=255)),
                ('audio_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('text', 'language')},
            },
        ),
        migrations.CreateModel(
            name='DefinitionModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('part_of_speech', models.CharField(max_length=50)),
                ('meaning', models.TextField()),
                ('example', models.TextField(blank=True)),
                ('synonyms', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, size=None)),
                ('order', models.IntegerField(default=0)),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='definitions', to='words.wordmodel')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
