/* tslint:disable */
/* eslint-disable */
/**
 * LexiFlow API
 * Reading assistant backend
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, replaceWithSerializableTypeIfNeeded } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError, operationServerMap } from './base';

/**
 * Serializer for Definition domain entity.  Handles serialization of word definitions including part of speech, meaning, examples, and synonyms.
 */
export interface Definition {
    'id': string;
    'meaning': string;
    'part_of_speech': string;
    'example'?: string | null;
    'synonyms'?: Array<string>;
    'order'?: number;
}
/**
 * * `small` - small * `medium` - medium * `large` - large
 */

export const FontSizeEnum = {
    Small: 'small',
    Medium: 'medium',
    Large: 'large',
} as const;

export type FontSizeEnum = typeof FontSizeEnum[keyof typeof FontSizeEnum];


export interface HistoryListRetrieve200Response {
    'count'?: number;
}
/**
 * Serializer for User domain entity.  Handles user profile data for registration and profile updates.
 */
export interface PatchedUser {
    'id'?: string;
    'email'?: string;
    'full_name'?: string | null;
    'avatar_url'?: string | null;
    'created_at'?: string;
    'updated_at'?: string;
}
/**
 * Serializer for UserPreferences domain entity.  Handles user UI and reading preferences.
 */
export interface PatchedUserPreferences {
    'id'?: string;
    'user_id'?: string;
    'is_dark_mode'?: boolean;
    'language'?: string;
    'notifications_enabled'?: boolean;
    'font_size'?: FontSizeEnum;
    'reading_line_height'?: number;
}


/**
 * Serializer for User domain entity.  Handles user profile data for registration and profile updates.
 */
export interface User {
    'id': string;
    'email': string;
    'full_name'?: string | null;
    'avatar_url'?: string | null;
    'created_at': string;
    'updated_at': string;
}
/**
 * Serializer for UserPreferences domain entity.  Handles user UI and reading preferences.
 */
export interface UserPreferences {
    'id': string;
    'user_id': string;
    'is_dark_mode'?: boolean;
    'language'?: string;
    'notifications_enabled'?: boolean;
    'font_size'?: FontSizeEnum;
    'reading_line_height'?: number;
}


/**
 * Serializer for user registration.  Includes password field for registration (not returned in responses).
 */
export interface UserRegistration {
    'email': string;
    'password': string;
    'full_name'?: string | null;
}
export interface VocabularyEntry {
    'id': string;
    'user_id': string;
    'word_id': string;
    'word_text': string;
    'meaning': string;
    'saved_at': string;
    'review_count': number;
    'last_reviewed_at': string;
}
/**
 * Serializer for Word domain entity.  Handles serialization of complete word entries including definitions, pronunciation, and metadata.
 */
export interface Word {
    'id': string;
    'text': string;
    'language': string;
    'phonetic'?: string | null;
    'audio_url'?: string | null;
    'created_at': string;
    'definitions': Array<Definition>;
}

/**
 * AnalyticsApi - axios parameter creator
 */
export const AnalyticsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Get statistics about user\'s word lookups.
         * @summary Get lookup statistics
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        analyticsLookupsRetrieve: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/analytics/lookups/`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication jwtAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Get statistics about user\'s reading sessions.
         * @summary Get reading session statistics
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        analyticsReadingSessionsRetrieve: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/analytics/reading-sessions/`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication jwtAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Get comprehensive statistics for the current user including reading sessions and lookups.
         * @summary Get user statistics
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        analyticsStatsRetrieve: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/analytics/stats/`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication jwtAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * AnalyticsApi - functional programming interface
 */
export const AnalyticsApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = AnalyticsApiAxiosParamCreator(configuration)
    return {
        /**
         * Get statistics about user\'s word lookups.
         * @summary Get lookup statistics
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async analyticsLookupsRetrieve(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<{ [key: string]: any; }>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.analyticsLookupsRetrieve(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AnalyticsApi.analyticsLookupsRetrieve']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Get statistics about user\'s reading sessions.
         * @summary Get reading session statistics
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async analyticsReadingSessionsRetrieve(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<{ [key: string]: any; }>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.analyticsReadingSessionsRetrieve(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AnalyticsApi.analyticsReadingSessionsRetrieve']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Get comprehensive statistics for the current user including reading sessions and lookups.
         * @summary Get user statistics
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async analyticsStatsRetrieve(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<{ [key: string]: any; }>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.analyticsStatsRetrieve(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AnalyticsApi.analyticsStatsRetrieve']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * AnalyticsApi - factory interface
 */
export const AnalyticsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = AnalyticsApiFp(configuration)
    return {
        /**
         * Get statistics about user\'s word lookups.
         * @summary Get lookup statistics
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        analyticsLookupsRetrieve(options?: RawAxiosRequestConfig): AxiosPromise<{ [key: string]: any; }> {
            return localVarFp.analyticsLookupsRetrieve(options).then((request) => request(axios, basePath));
        },
        /**
         * Get statistics about user\'s reading sessions.
         * @summary Get reading session statistics
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        analyticsReadingSessionsRetrieve(options?: RawAxiosRequestConfig): AxiosPromise<{ [key: string]: any; }> {
            return localVarFp.analyticsReadingSessionsRetrieve(options).then((request) => request(axios, basePath));
        },
        /**
         * Get comprehensive statistics for the current user including reading sessions and lookups.
         * @summary Get user statistics
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        analyticsStatsRetrieve(options?: RawAxiosRequestConfig): AxiosPromise<{ [key: string]: any; }> {
            return localVarFp.analyticsStatsRetrieve(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * AnalyticsApi - object-oriented interface
 */
export class AnalyticsApi extends BaseAPI {
    /**
     * Get statistics about user\'s word lookups.
     * @summary Get lookup statistics
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public analyticsLookupsRetrieve(options?: RawAxiosRequestConfig) {
        return AnalyticsApiFp(this.configuration).analyticsLookupsRetrieve(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Get statistics about user\'s reading sessions.
     * @summary Get reading session statistics
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public analyticsReadingSessionsRetrieve(options?: RawAxiosRequestConfig) {
        return AnalyticsApiFp(this.configuration).analyticsReadingSessionsRetrieve(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Get comprehensive statistics for the current user including reading sessions and lookups.
     * @summary Get user statistics
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public analyticsStatsRetrieve(options?: RawAxiosRequestConfig) {
        return AnalyticsApiFp(this.configuration).analyticsStatsRetrieve(options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * AuthApi - axios parameter creator
 */
export const AuthApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Update the current user\'s preferences.
         * @summary Update user preferences
         * @param {PatchedUserPreferences} [patchedUserPreferences] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        authPreferencesPartialUpdate: async (patchedUserPreferences?: PatchedUserPreferences, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/auth/preferences/`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication jwtAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(patchedUserPreferences, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Get the current user\'s preferences.
         * @summary Get user preferences
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        authPreferencesRetrieve: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/auth/preferences/`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication jwtAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Get the current user\'s profile information.
         * @summary Get user profile
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        authProfileRetrieve: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/auth/profile/`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication jwtAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Create a new user account and return authentication tokens.
         * @summary Register new user
         * @param {UserRegistration} userRegistration 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        authRegisterCreate: async (userRegistration: UserRegistration, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'userRegistration' is not null or undefined
            assertParamExists('authRegisterCreate', 'userRegistration', userRegistration)
            const localVarPath = `/api/auth/register/`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication jwtAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(userRegistration, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Update the current user\'s profile information.
         * @summary Update user profile
         * @param {PatchedUser} [patchedUser] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        authUpdateProfilePartialUpdate: async (patchedUser?: PatchedUser, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/auth/update_profile/`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication jwtAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(patchedUser, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * AuthApi - functional programming interface
 */
export const AuthApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = AuthApiAxiosParamCreator(configuration)
    return {
        /**
         * Update the current user\'s preferences.
         * @summary Update user preferences
         * @param {PatchedUserPreferences} [patchedUserPreferences] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async authPreferencesPartialUpdate(patchedUserPreferences?: PatchedUserPreferences, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<UserPreferences>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.authPreferencesPartialUpdate(patchedUserPreferences, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AuthApi.authPreferencesPartialUpdate']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Get the current user\'s preferences.
         * @summary Get user preferences
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async authPreferencesRetrieve(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<UserPreferences>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.authPreferencesRetrieve(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AuthApi.authPreferencesRetrieve']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Get the current user\'s profile information.
         * @summary Get user profile
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async authProfileRetrieve(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<User>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.authProfileRetrieve(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AuthApi.authProfileRetrieve']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Create a new user account and return authentication tokens.
         * @summary Register new user
         * @param {UserRegistration} userRegistration 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async authRegisterCreate(userRegistration: UserRegistration, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<{ [key: string]: any; }>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.authRegisterCreate(userRegistration, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AuthApi.authRegisterCreate']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Update the current user\'s profile information.
         * @summary Update user profile
         * @param {PatchedUser} [patchedUser] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async authUpdateProfilePartialUpdate(patchedUser?: PatchedUser, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<User>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.authUpdateProfilePartialUpdate(patchedUser, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AuthApi.authUpdateProfilePartialUpdate']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * AuthApi - factory interface
 */
export const AuthApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = AuthApiFp(configuration)
    return {
        /**
         * Update the current user\'s preferences.
         * @summary Update user preferences
         * @param {PatchedUserPreferences} [patchedUserPreferences] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        authPreferencesPartialUpdate(patchedUserPreferences?: PatchedUserPreferences, options?: RawAxiosRequestConfig): AxiosPromise<UserPreferences> {
            return localVarFp.authPreferencesPartialUpdate(patchedUserPreferences, options).then((request) => request(axios, basePath));
        },
        /**
         * Get the current user\'s preferences.
         * @summary Get user preferences
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        authPreferencesRetrieve(options?: RawAxiosRequestConfig): AxiosPromise<UserPreferences> {
            return localVarFp.authPreferencesRetrieve(options).then((request) => request(axios, basePath));
        },
        /**
         * Get the current user\'s profile information.
         * @summary Get user profile
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        authProfileRetrieve(options?: RawAxiosRequestConfig): AxiosPromise<User> {
            return localVarFp.authProfileRetrieve(options).then((request) => request(axios, basePath));
        },
        /**
         * Create a new user account and return authentication tokens.
         * @summary Register new user
         * @param {UserRegistration} userRegistration 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        authRegisterCreate(userRegistration: UserRegistration, options?: RawAxiosRequestConfig): AxiosPromise<{ [key: string]: any; }> {
            return localVarFp.authRegisterCreate(userRegistration, options).then((request) => request(axios, basePath));
        },
        /**
         * Update the current user\'s profile information.
         * @summary Update user profile
         * @param {PatchedUser} [patchedUser] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        authUpdateProfilePartialUpdate(patchedUser?: PatchedUser, options?: RawAxiosRequestConfig): AxiosPromise<User> {
            return localVarFp.authUpdateProfilePartialUpdate(patchedUser, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * AuthApi - object-oriented interface
 */
export class AuthApi extends BaseAPI {
    /**
     * Update the current user\'s preferences.
     * @summary Update user preferences
     * @param {PatchedUserPreferences} [patchedUserPreferences] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public authPreferencesPartialUpdate(patchedUserPreferences?: PatchedUserPreferences, options?: RawAxiosRequestConfig) {
        return AuthApiFp(this.configuration).authPreferencesPartialUpdate(patchedUserPreferences, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Get the current user\'s preferences.
     * @summary Get user preferences
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public authPreferencesRetrieve(options?: RawAxiosRequestConfig) {
        return AuthApiFp(this.configuration).authPreferencesRetrieve(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Get the current user\'s profile information.
     * @summary Get user profile
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public authProfileRetrieve(options?: RawAxiosRequestConfig) {
        return AuthApiFp(this.configuration).authProfileRetrieve(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Create a new user account and return authentication tokens.
     * @summary Register new user
     * @param {UserRegistration} userRegistration 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public authRegisterCreate(userRegistration: UserRegistration, options?: RawAxiosRequestConfig) {
        return AuthApiFp(this.configuration).authRegisterCreate(userRegistration, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Update the current user\'s profile information.
     * @summary Update user profile
     * @param {PatchedUser} [patchedUser] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public authUpdateProfilePartialUpdate(patchedUser?: PatchedUser, options?: RawAxiosRequestConfig) {
        return AuthApiFp(this.configuration).authUpdateProfilePartialUpdate(patchedUser, options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * HistoryApi - axios parameter creator
 */
export const HistoryApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Delete all lookup history for the current user.
         * @summary Clear lookup history
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        historyClearDestroy: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/history/clear/`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication jwtAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Get total number of word lookups for the user.
         * @summary Get lookup count
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        historyCountRetrieve: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/history/count/`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication jwtAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Get number of lookups since a specific date.
         * @summary Get lookup count since date
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        historyCountSinceRetrieve: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/history/count-since/`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication jwtAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Get number of lookups since a specific date.
         * @summary Get lookup count since date
         * @param {string} since ISO 8601 datetime (e.g., 2024-01-01T00:00:00Z)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        historyListRetrieve: async (since: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'since' is not null or undefined
            assertParamExists('historyListRetrieve', 'since', since)
            const localVarPath = `/api/history/list/`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication jwtAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (since !== undefined) {
                localVarQueryParameter['since'] = (since as any instanceof Date) ?
                    (since as any).toISOString() :
                    since;
            }

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * HistoryApi - functional programming interface
 */
export const HistoryApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = HistoryApiAxiosParamCreator(configuration)
    return {
        /**
         * Delete all lookup history for the current user.
         * @summary Clear lookup history
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async historyClearDestroy(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<{ [key: string]: any; }>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.historyClearDestroy(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['HistoryApi.historyClearDestroy']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Get total number of word lookups for the user.
         * @summary Get lookup count
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async historyCountRetrieve(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<{ [key: string]: any; }>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.historyCountRetrieve(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['HistoryApi.historyCountRetrieve']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Get number of lookups since a specific date.
         * @summary Get lookup count since date
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async historyCountSinceRetrieve(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<{ [key: string]: any; }>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.historyCountSinceRetrieve(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['HistoryApi.historyCountSinceRetrieve']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Get number of lookups since a specific date.
         * @summary Get lookup count since date
         * @param {string} since ISO 8601 datetime (e.g., 2024-01-01T00:00:00Z)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async historyListRetrieve(since: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<HistoryListRetrieve200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.historyListRetrieve(since, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['HistoryApi.historyListRetrieve']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * HistoryApi - factory interface
 */
export const HistoryApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = HistoryApiFp(configuration)
    return {
        /**
         * Delete all lookup history for the current user.
         * @summary Clear lookup history
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        historyClearDestroy(options?: RawAxiosRequestConfig): AxiosPromise<{ [key: string]: any; }> {
            return localVarFp.historyClearDestroy(options).then((request) => request(axios, basePath));
        },
        /**
         * Get total number of word lookups for the user.
         * @summary Get lookup count
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        historyCountRetrieve(options?: RawAxiosRequestConfig): AxiosPromise<{ [key: string]: any; }> {
            return localVarFp.historyCountRetrieve(options).then((request) => request(axios, basePath));
        },
        /**
         * Get number of lookups since a specific date.
         * @summary Get lookup count since date
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        historyCountSinceRetrieve(options?: RawAxiosRequestConfig): AxiosPromise<{ [key: string]: any; }> {
            return localVarFp.historyCountSinceRetrieve(options).then((request) => request(axios, basePath));
        },
        /**
         * Get number of lookups since a specific date.
         * @summary Get lookup count since date
         * @param {string} since ISO 8601 datetime (e.g., 2024-01-01T00:00:00Z)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        historyListRetrieve(since: string, options?: RawAxiosRequestConfig): AxiosPromise<HistoryListRetrieve200Response> {
            return localVarFp.historyListRetrieve(since, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * HistoryApi - object-oriented interface
 */
export class HistoryApi extends BaseAPI {
    /**
     * Delete all lookup history for the current user.
     * @summary Clear lookup history
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public historyClearDestroy(options?: RawAxiosRequestConfig) {
        return HistoryApiFp(this.configuration).historyClearDestroy(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Get total number of word lookups for the user.
     * @summary Get lookup count
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public historyCountRetrieve(options?: RawAxiosRequestConfig) {
        return HistoryApiFp(this.configuration).historyCountRetrieve(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Get number of lookups since a specific date.
     * @summary Get lookup count since date
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public historyCountSinceRetrieve(options?: RawAxiosRequestConfig) {
        return HistoryApiFp(this.configuration).historyCountSinceRetrieve(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Get number of lookups since a specific date.
     * @summary Get lookup count since date
     * @param {string} since ISO 8601 datetime (e.g., 2024-01-01T00:00:00Z)
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public historyListRetrieve(since: string, options?: RawAxiosRequestConfig) {
        return HistoryApiFp(this.configuration).historyListRetrieve(since, options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * VocabularyApi - axios parameter creator
 */
export const VocabularyApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Check if a specific word is saved in user\'s vocabulary.
         * @summary Check if word is saved
         * @param {string} wordId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        vocabularyIsSavedRetrieve: async (wordId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'wordId' is not null or undefined
            assertParamExists('vocabularyIsSavedRetrieve', 'wordId', wordId)
            const localVarPath = `/api/vocabulary/is-saved/{word_id}/`
                .replace(`{${"word_id"}}`, encodeURIComponent(String(wordId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication jwtAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Get all words saved by the user.
         * @summary Get user vocabulary
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        vocabularyListList: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/vocabulary/list/`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication jwtAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Remove a word from the user\'s personal vocabulary list.
         * @summary Remove word from vocabulary
         * @param {string} wordId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        vocabularyRemoveDestroy: async (wordId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'wordId' is not null or undefined
            assertParamExists('vocabularyRemoveDestroy', 'wordId', wordId)
            const localVarPath = `/api/vocabulary/remove/{word_id}/`
                .replace(`{${"word_id"}}`, encodeURIComponent(String(wordId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication jwtAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Save a word to the user\'s personal vocabulary list.
         * @summary Save word to vocabulary
         * @param {string} wordId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        vocabularySaveCreate: async (wordId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'wordId' is not null or undefined
            assertParamExists('vocabularySaveCreate', 'wordId', wordId)
            const localVarPath = `/api/vocabulary/save/{word_id}/`
                .replace(`{${"word_id"}}`, encodeURIComponent(String(wordId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication jwtAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Search user\'s saved vocabulary by word text.
         * @summary Search vocabulary
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        vocabularySearchList: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/vocabulary/search/`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication jwtAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * VocabularyApi - functional programming interface
 */
export const VocabularyApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = VocabularyApiAxiosParamCreator(configuration)
    return {
        /**
         * Check if a specific word is saved in user\'s vocabulary.
         * @summary Check if word is saved
         * @param {string} wordId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async vocabularyIsSavedRetrieve(wordId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<{ [key: string]: any; }>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.vocabularyIsSavedRetrieve(wordId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['VocabularyApi.vocabularyIsSavedRetrieve']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Get all words saved by the user.
         * @summary Get user vocabulary
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async vocabularyListList(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<VocabularyEntry>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.vocabularyListList(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['VocabularyApi.vocabularyListList']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Remove a word from the user\'s personal vocabulary list.
         * @summary Remove word from vocabulary
         * @param {string} wordId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async vocabularyRemoveDestroy(wordId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.vocabularyRemoveDestroy(wordId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['VocabularyApi.vocabularyRemoveDestroy']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Save a word to the user\'s personal vocabulary list.
         * @summary Save word to vocabulary
         * @param {string} wordId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async vocabularySaveCreate(wordId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<VocabularyEntry>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.vocabularySaveCreate(wordId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['VocabularyApi.vocabularySaveCreate']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Search user\'s saved vocabulary by word text.
         * @summary Search vocabulary
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async vocabularySearchList(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<VocabularyEntry>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.vocabularySearchList(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['VocabularyApi.vocabularySearchList']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * VocabularyApi - factory interface
 */
export const VocabularyApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = VocabularyApiFp(configuration)
    return {
        /**
         * Check if a specific word is saved in user\'s vocabulary.
         * @summary Check if word is saved
         * @param {string} wordId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        vocabularyIsSavedRetrieve(wordId: string, options?: RawAxiosRequestConfig): AxiosPromise<{ [key: string]: any; }> {
            return localVarFp.vocabularyIsSavedRetrieve(wordId, options).then((request) => request(axios, basePath));
        },
        /**
         * Get all words saved by the user.
         * @summary Get user vocabulary
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        vocabularyListList(options?: RawAxiosRequestConfig): AxiosPromise<Array<VocabularyEntry>> {
            return localVarFp.vocabularyListList(options).then((request) => request(axios, basePath));
        },
        /**
         * Remove a word from the user\'s personal vocabulary list.
         * @summary Remove word from vocabulary
         * @param {string} wordId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        vocabularyRemoveDestroy(wordId: string, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.vocabularyRemoveDestroy(wordId, options).then((request) => request(axios, basePath));
        },
        /**
         * Save a word to the user\'s personal vocabulary list.
         * @summary Save word to vocabulary
         * @param {string} wordId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        vocabularySaveCreate(wordId: string, options?: RawAxiosRequestConfig): AxiosPromise<VocabularyEntry> {
            return localVarFp.vocabularySaveCreate(wordId, options).then((request) => request(axios, basePath));
        },
        /**
         * Search user\'s saved vocabulary by word text.
         * @summary Search vocabulary
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        vocabularySearchList(options?: RawAxiosRequestConfig): AxiosPromise<Array<VocabularyEntry>> {
            return localVarFp.vocabularySearchList(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * VocabularyApi - object-oriented interface
 */
export class VocabularyApi extends BaseAPI {
    /**
     * Check if a specific word is saved in user\'s vocabulary.
     * @summary Check if word is saved
     * @param {string} wordId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public vocabularyIsSavedRetrieve(wordId: string, options?: RawAxiosRequestConfig) {
        return VocabularyApiFp(this.configuration).vocabularyIsSavedRetrieve(wordId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Get all words saved by the user.
     * @summary Get user vocabulary
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public vocabularyListList(options?: RawAxiosRequestConfig) {
        return VocabularyApiFp(this.configuration).vocabularyListList(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Remove a word from the user\'s personal vocabulary list.
     * @summary Remove word from vocabulary
     * @param {string} wordId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public vocabularyRemoveDestroy(wordId: string, options?: RawAxiosRequestConfig) {
        return VocabularyApiFp(this.configuration).vocabularyRemoveDestroy(wordId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Save a word to the user\'s personal vocabulary list.
     * @summary Save word to vocabulary
     * @param {string} wordId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public vocabularySaveCreate(wordId: string, options?: RawAxiosRequestConfig) {
        return VocabularyApiFp(this.configuration).vocabularySaveCreate(wordId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Search user\'s saved vocabulary by word text.
     * @summary Search vocabulary
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public vocabularySearchList(options?: RawAxiosRequestConfig) {
        return VocabularyApiFp(this.configuration).vocabularySearchList(options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * WordsApi - axios parameter creator
 */
export const WordsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Look up a word definition with caching and external API fallback. Records lookup in history.
         * @summary Look up a word
         * @param {string} word 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        wordsLookupRetrieve: async (word: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'word' is not null or undefined
            assertParamExists('wordsLookupRetrieve', 'word', word)
            const localVarPath = `/api/words/lookup/{word}/`
                .replace(`{${"word"}}`, encodeURIComponent(String(word)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication jwtAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * WordsApi - functional programming interface
 */
export const WordsApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = WordsApiAxiosParamCreator(configuration)
    return {
        /**
         * Look up a word definition with caching and external API fallback. Records lookup in history.
         * @summary Look up a word
         * @param {string} word 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async wordsLookupRetrieve(word: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Word>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.wordsLookupRetrieve(word, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['WordsApi.wordsLookupRetrieve']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * WordsApi - factory interface
 */
export const WordsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = WordsApiFp(configuration)
    return {
        /**
         * Look up a word definition with caching and external API fallback. Records lookup in history.
         * @summary Look up a word
         * @param {string} word 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        wordsLookupRetrieve(word: string, options?: RawAxiosRequestConfig): AxiosPromise<Word> {
            return localVarFp.wordsLookupRetrieve(word, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * WordsApi - object-oriented interface
 */
export class WordsApi extends BaseAPI {
    /**
     * Look up a word definition with caching and external API fallback. Records lookup in history.
     * @summary Look up a word
     * @param {string} word 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public wordsLookupRetrieve(word: string, options?: RawAxiosRequestConfig) {
        return WordsApiFp(this.configuration).wordsLookupRetrieve(word, options).then((request) => request(this.axios, this.basePath));
    }
}



